### ISSUE TITLE
Link in readme is not working (error 404)

### ISSUE THREAD

**Issue by antododo** [cds-consensys/drizzle-event-demo#1]
The link in the readme [Drizzle and Contract Events tutorial](https://www.truffleframework.com/tutorials/drizzle-and-contract-events) is not working.
I searched Truffle tutorials and I didn't see a recent tutorial about Drizzle. 
Maybe not publish yet?
Anyway, I looked the commit d2ad834506353f35045138e5ff5c08d18d776be4 to be able to see the readme.

**Comment by cds-amal** [comment]
@antododo You're correct. It's still a wip. I'll tag you when it's ready!

**Comment by cds-amal** [comment]
@antododo The [Drizzle and Contract Events tutorial](https://www.truffleframework.com/tutorials/drizzle-and-contract-events) is up! Let me know if you run into any issues with it.

**Comment by antododo** [comment]
Cool thanks! Will check when I can!
